// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import process from "node:process";




// Determine if we are running a migration or push command
const isMigration = process.argv.some((arg) =>
  arg.includes("migrate") || arg.includes("push")
);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrations/push to bypass connection pooling (e.g. PgBouncer)
    // Fallback to DATABASE_URL if DIRECT_URL is not set
    url: (isMigration && process.env.DIRECT_URL)
      ? process.env.DIRECT_URL
      : process.env.DATABASE_URL,
  },
});
